[build]
    command = "yarn build"
    publish = "dist"

[context.branch-deploy]
    command = "yarn build --mode staging"

[[redirects]]
    from = "/admin"
    to = "https://na-sponsorship-api-dev.herokuapp.com/admin"