import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faTimes,
    faUser,
    faGift,
    faCheckCircle,
    faCaretRight,
    faCaretLeft,
    faDollarSign,
    faQuestionCircle,
    faShieldAlt,
    faLongArrowAltLeft,
    faPhone,
    faEnvelope,
    faSpinner,
    faWallet,
    faBars,
    faCaretUp,
    faCross,
    faSchool,
    faChild
} from "@fortawesome/free-solid-svg-icons";
import {
    faFacebookF,
    faTwitter,
    faYoutube,
    faInstagram,
} from "@fortawesome/free-brands-svg-icons";

library.add(
    faFacebookF,
    faTwitter,
    faYoutube,
    faInstagram,
    faTimes,
    faUser,
    faGift,
    faCheckCircle,
    faCaretRight,
    faCaretLeft,
    faDollarSign,
    faQuestionCircle,
    faShieldAlt,
    faLongArrowAltLeft,
    faPhone,
    faEnvelope,
    faWallet,
    faSpinner,
    faBars,
    faCaretUp,
    faCheckCircle,
    faCross,
    faSchool,
    faChild
);